language: python
dist: trusty
python:
  - "3.5"

before_install:
  - npm install eslint stylelint@7.8.0 stylelint-config-wikimedia

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py install

script: 
  - nosetests
  - timeout --preserve-status 8s wikilabels dev_server
  - ./node_modules/.bin/eslint .
  - ./node_modules/.bin/stylelint "wikilabels/wsgi/static/css/*.css"
