language: python
dist: trusty
python:
  - "3.5"

before_install:
  - npm install eslint stylelint@7.8.0 stylelint-config-wikimedia

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py install
  - pip install codecov
  - pip install flake8

script:
  - flake8 . --ignore=E722
  - coverage run --source wikilabels -m pytest -m "not nottravis"
  - timeout --preserve-status 8s wikilabels dev_server
  - ./node_modules/.bin/eslint .
  - ./node_modules/.bin/stylelint "wikilabels/wsgi/static/css/*.css"

after_success:
  - coverage report
  - codecov
